### ISSUE TITLE
Invalid schema error is not always informative

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pephub#292]
After @khoroshevskyi  and I performed some manual testing validating a PEP with the bedboss schema, it appears that if a field is required AND has an enum it does not give an informative error if it fails validation:
![image](https://github.com/pepkit/pephub/assets/125581724/d6a51dbf-538f-49cc-b812-a0718d5edf6f)

PEP used for Testing:
https://pephub.databio.org/donaldcampbelljr/test_minimal_bedboss?tag=samples

From the bedboss schema:
https://schema.databio.org/?namespace=pipelines&schema=bedboss

```
input_type:
  type: string
  description: "file format"
  enum: [ "bigWig", "bigBed", "bed", "wig", "bedGraph" ]
  
required:
  - sample_name
  - input_file
  - input_type
  - genome

```
