### ISSUE TITLE
PEPhub wont save my PEP

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#414]
I can't get PEPhub to save my PEP. I have tried two ways:

1. File upload interface
2. Manually pasting the values in

I can confirm that locally with `peppy==0.40.7`, it will consume the PEP happily and let me traverse the sample/subsample table(s).

### Steps to reproduce:
1. Log in to PEPhub
2. Navigate to your profile
3. Click "Add" at the top right
4. Navigate to the "upload PEP" form
5. Select the attached files in the file selector
6. Click, submit
7. Observe error

### Files
[samples.csv](https://github.com/user-attachments/files/18564912/samples.csv)
[subsamples.csv](https://github.com/user-attachments/files/18564913/subsamples.csv)

It wont let me upload a `yaml`, but this is the config:
```yaml
# pep_config.yaml
pep_version: 2.1.0
sample_table: samples.csv
subsample_table: subsamples.csv
sample_table_index: id
subsample_table_index: file_uuid
name: atlas
description: Datasets (fastqs) to be used in the training of Atacformer.
```
