### ISSUE TITLE
derived sample_names cannot be modified

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#439]
The sample_name in PEPhub can be derived and modified in the config file.

Unfortunately, because of this, if sample_name does not exist in the sample table, modifying of the project becomes impossible.
An exception occurs when trying to retrieve the sample name from a sample table that was not initialized by peppy. The error is happening in pepdbagent.

![Image](https://github.com/user-attachments/assets/39b1024d-d088-475a-a59f-ab619cf14fbf)

Example pep:
```
pep_version: 2.1.0
sample_table: samples.csv
name: cm4ai_images
description: ''
sample_modifiers:
  append:
    sample_name: key
  derive:
    attributes:
    - sample_name
    sources:
      key: '{Gene_Name}_{Treatment}'

```
csv file:

AntibodyID | ENSEMBLID | Gene_Name | Treatment | PlateID | Well
-- | -- | -- | -- | -- | --
CAB005042  | ens123 | EIF5A | Paclitaxel | 3 | C2
CAB005042 | ens124 | EIF5A | Vorinostat | 3 | C2
CAB005042 | ens125 | EIF5A | untreated | 3 | C2
